[package]
name = "rust-firework"
version = "0.1.0"
authors = ["Rudy Nappée <r.nappee@prisma-tic.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.19.1"
rand = "0.8.0"
palette = "0.5.0"
