name: Rust

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
            - os: ubuntu-latest
              artifact_name: rust-firework
              asset_name: rust-firework-linux-x64
            - os: windows-latest
              artifact_name: rust-firework.exe
              asset_name: rust-firework-windows-x64.exe
            - os: macos-latest
              artifact_name: rust-firework
              asset_name: rust-firework-macos-x64

    steps:
    - uses: actions/checkout@v2

    - run: echo $RUNNER_OS

    - run: |
      if [ "$RUNNER_OS" == "Linux" ]; then
      sudo apt-get install libxkbcommon-x11-dev
      fi
      
    - run: cargo build --release --verbose

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
#    - name: Run tests
#      run: cargo test --verbose
